//=======================================================================================
//
// Copyright (C) 2010-2011 Asia-Peak Technologies, Inc. All Rights Reserved.
// 
// All the code, text, graphics, media, design, programs and other works are
// protected by copyright law. Unauthorized reproduction or redistribution of them, 
// or any portion of them, are forbidden.
// 
//=======================================================================================
//---------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------

using System;

namespace Portal.Infrastructure.Exceptions
{	
	public static class ErrorCodes
    {
		public static class NumbericCodes
		{
			/// <summary>
			/// Internal error
			/// </summary>
			public const int InternalError = unchecked((int)0x800F0001);

			/// <summary>
			/// The request parameter can not null
			/// </summary>
			public const int ValidationRequestParameterNull = unchecked((int)0x800F0002);

			/// <summary>
			/// {0}不能为空
			/// </summary>
			public const int ArgumentCannotBeNullOrEmptyString = unchecked((int)0x800F0003);

			/// <summary>
			/// {0}不存在
			/// </summary>
			public const int ArgumentCannotBeNull = unchecked((int)0x800F0004);

			/// <summary>
			/// Login failed
			/// </summary>
			public const int LoginFailed = unchecked((int)0x800F0101);

			/// <summary>
			/// Access denied
			/// </summary>
			public const int AccessDenied = unchecked((int)0x800F0102);

			/// <summary>
			/// 系统已存在相同的应用名称:{0}
			/// </summary>
			public const int ExistsSameApplicationName = unchecked((int)0x800F0501);

			/// <summary>
			/// 系统不存在此应用
			/// </summary>
			public const int NoFoundApplication = unchecked((int)0x800F0502);

			/// <summary>
			/// 系统已存在相同的应用英文名称:{0}
			/// </summary>
			public const int ExistsSameApplicationEnName = unchecked((int)0x800F0503);

			/// <summary>
			/// 当前用户已经为启用状态，不能再次转为启用状态
			/// </summary>
			public const int CannotChangeUserStateToEnabled = unchecked((int)0x800F0530);

			/// <summary>
			/// 当前用户已经为禁用状态，不能再次转为禁用状态
			/// </summary>
			public const int CannotChangeUserStateToDisabled = unchecked((int)0x800F0531);

			/// <summary>
			/// 系统已存在相同的用户名:{0}
			/// </summary>
			public const int ExistsSameUserLoginName = unchecked((int)0x800F0532);

			/// <summary>
			/// 用户名或密码无效
			/// </summary>
			public const int LoginNameOrPasswordInvalid = unchecked((int)0x800F0533);

			/// <summary>
			/// 已存在相同的角色名称
			/// </summary>
			public const int ExistsSameRoleName = unchecked((int)0x800F0534);

			/// <summary>
			/// 已存在相同的角色代码
			/// </summary>
			public const int ExistsSameRoleCode = unchecked((int)0x800F0535);

			/// <summary>
			/// 系统不存在角色代码:{0}
			/// </summary>
			public const int NoFoundRoleCode = unchecked((int)0x800F0536);

			/// <summary>
			/// 旧密码不匹配
			/// </summary>
			public const int OldPassowrdNotMatch = unchecked((int)0x800F0537);

			/// <summary>
			/// 系统已存在相同的员工号:{0}
			/// </summary>
			public const int ExistsSameEmployeeNo = unchecked((int)0x800F0538);

			/// <summary>
			/// 无效的Email
			/// </summary>
			public const int InvalidEmail = unchecked((int)0x800F0539);

			/// <summary>
			/// 密码不允许为空
			/// </summary>
			public const int PasswordCannotBeNull = unchecked((int)0x800F0540);

			/// <summary>
			/// 当前用户已被禁用
			/// </summary>
			public const int LoginNameIsApproved = unchecked((int)0x800F0541);

			/// <summary>
			/// 无效的手机号码
			/// </summary>
			public const int InvalidPhone = unchecked((int)0x800F0542);

			/// <summary>
			/// 用户名不允许为空
			/// </summary>
			public const int IdentityCannotBeNull = unchecked((int)0x800F0543);

			/// <summary>
			/// 调用来源不允许为空
			/// </summary>
			public const int SourceCannotBeNull = unchecked((int)0x800F0544);

			/// <summary>
			/// 用户{0}不存在
			/// </summary>
			public const int IdentityNotExist = unchecked((int)0x800F0545);

			/// <summary>
			/// 登陆名称不允许为空
			/// </summary>
			public const int LoginNameCannotBeNull = unchecked((int)0x800F0546);

			/// <summary>
			/// 邮箱不允许为空
			/// </summary>
			public const int EmailCannotBeNull = unchecked((int)0x800F0547);

			/// <summary>
			/// 系统不存在权限代码:{0}
			/// </summary>
			public const int NoFoundPermissionCode = unchecked((int)0x800F0550);

			/// <summary>
			/// 不支持的权限类型
			/// </summary>
			public const int UnSupportPermissionType = unchecked((int)0x800F0551);

			/// <summary>
			/// 已存在相同的权限名称
			/// </summary>
			public const int ExistsSamePermissionName = unchecked((int)0x800F0552);

			/// <summary>
			/// 当前应用不存在权限代码:{0}
			/// </summary>
			public const int AppNoFoundPermissionCode = unchecked((int)0x800F0553);

			/// <summary>
			/// 不存在该菜单ID:{0}
			/// </summary>
			public const int NoFoundMenuId = unchecked((int)0x800F0570);

			/// <summary>
			/// 菜单ID:{0}存在子菜单，不允许删除
			/// </summary>
			public const int MenuHasChild = unchecked((int)0x800F0571);

			/// <summary>
			/// 当前应用不存在该菜单ID:{0}
			/// </summary>
			public const int ApplicationNoFoundMenuId = unchecked((int)0x800F0572);

			/// <summary>
			/// 已存在相同的分组名称
			/// </summary>
			public const int ExistsSameApiPermissionGroupName = unchecked((int)0x800F0572);

			/// <summary>
			/// 已存在相同的分组编码
			/// </summary>
			public const int ExistsSameApiPermissionGroupCode = unchecked((int)0x800F0573);

			/// <summary>
			/// 不存在API权限分组代码:{0}
			/// </summary>
			public const int NoFoundApiPermissionGroupCode = unchecked((int)0x800F0574);

			/// <summary>
			/// 需要对外开放的权限码:{0}
			/// </summary>
			public const int IsOpenedPermissionCode = unchecked((int)0x800F0575);

			/// <summary>
			/// 需要客户授权的权限代码:{0}
			/// </summary>
			public const int IsCustomerGrantedPermissionCode = unchecked((int)0x800F0576);

			/// <summary>
			/// 已存在相同的权限编码:{0}
			/// </summary>
			public const int ExistsSamePermissionCode = unchecked((int)0x800F0577);

			/// <summary>
			/// Token已过期，不能设置为启用
			/// </summary>
			public const int TokenExpiredCannotSetEnable = unchecked((int)0x800F0600);

			/// <summary>
			/// 授权码已过期或已使用，不能设置为启用
			/// </summary>
			public const int AuthorizationCodeCannotSetEnable = unchecked((int)0x800F0601);

			/// <summary>
			/// 开发者应用程序名称不能为空
			/// </summary>
			public const int DeveloperApplicatinNameCannotBeNull = unchecked((int)0x800F0602);

			/// <summary>
			/// 开发者应用程序所属账号不能为空
			/// </summary>
			public const int DeveloperApplicatinUserCannotBeNull = unchecked((int)0x800F0603);

			/// <summary>
			/// 开发者应用程序回调地址不能为空
			/// </summary>
			public const int DeveloperApplicatinCallbackUrlCannotBeNull = unchecked((int)0x800F0604);

			/// <summary>
			/// 开发者应用程序在非开发中状态不能提交审核
			/// </summary>
			public const int DeveloperApplicatinInvalidStateCannotSubmitToApprove = unchecked((int)0x800F0605);

			/// <summary>
			/// 开发者应用程序不是审核通过，可能在非法的状态下提审
			/// </summary>
			public const int DeveloperApplicatinInvalidStateCannotBeApproved = unchecked((int)0x800F0606);

			/// <summary>
			/// 开发者应用程序在当前的状态下不能驳回
			/// </summary>
			public const int DeveloperApplicatinInvalidStateToBeReject = unchecked((int)0x800F0607);

			/// <summary>
			/// 不支持的请求授权类型
			/// </summary>
			public const int CustomerAuthorizationUnsupportType = unchecked((int)0x800F0608);

			/// <summary>
			/// 请求授权的应用不存在
			/// </summary>
			public const int CustomerAuthorizationAppNotExist = unchecked((int)0x800F0609);

			/// <summary>
			/// 请求授权应用的重定向地址与应用注册时回调地址非同源
			/// </summary>
			public const int CustomerAuthorizationRedirectUrlIsNotCognatedWithRegisterCallbcakUrl = unchecked((int)0x800F0610);

			/// <summary>
			/// 未指定授权范围参数
			/// </summary>
			public const int CustomerAuthorizationScopeMustHasVal = unchecked((int)0x800F0611);

			/// <summary>
			/// 请求的授权部分不存在，请重新确认授权范围
			/// </summary>
			public const int CustomerAuthorizationScopePartNotExist = unchecked((int)0x800F0612);

			/// <summary>
			/// 未指定请求授权响应类型(responseType)
			/// </summary>
			public const int CustomerAuthorizationResponseTypeMissing = unchecked((int)0x800F0613);

			/// <summary>
			/// 未指定重定向参数(redirect_uri)
			/// </summary>
			public const int CustomerAuthorizationRedirectUriMissing = unchecked((int)0x800F0614);

			/// <summary>
			/// 未指定应用Clientid参数
			/// </summary>
			public const int CustomerAuthorizationClientIdMissing = unchecked((int)0x800F0615);

			/// <summary>
			/// 未指定应用授权范围参数(scope)
			/// </summary>
			public const int CustomerAuthorizationScopeMissing = unchecked((int)0x800F0616);

			/// <summary>
			/// 授权范围与应用授权不匹配，请重新确认授权范围(scope)
			/// </summary>
			public const int CustomerAuthorizationScopeNotMatch = unchecked((int)0x800F0617);

			/// <summary>
			/// 请求访问Token应用密钥参数未指定.(Client_secret)
			/// </summary>
			public const int RequestAccessTokenSecretMissing = unchecked((int)0x800F0618);

			/// <summary>
			/// 请求访问Token应用密钥不匹配.(Client_secret)
			/// </summary>
			public const int RequestAccessTokenSecretNotMatch = unchecked((int)0x800F0619);

			/// <summary>
			/// 请求访问Token授权类型未指定.(Grant_type)
			/// </summary>
			public const int RequestAccessTokenGrantTypeMissing = unchecked((int)0x800F0620);

			/// <summary>
			/// 请求访问Token授权类型指定错误，目前支持authorization_code和refresh_token两种方式
			/// </summary>
			public const int RequestAccessTokenGrantTypeError = unchecked((int)0x800F0621);

			/// <summary>
			/// 请求访问Token授权未指定授权码.
			/// </summary>
			public const int RequestAccessTokenAuthorizationCodeMissing = unchecked((int)0x800F0622);

			/// <summary>
			/// 请求访问的授权码不存在.
			/// </summary>
			public const int RequestAccessTokenAuthorizationCodeNotExist = unchecked((int)0x800F0623);

			/// <summary>
			/// 请求访问的授权码无效.
			/// </summary>
			public const int RequestAccessTokenAuthorizationCodeError = unchecked((int)0x800F0622);

			/// <summary>
			/// 请求访问的授权码不属于当前应用
			/// </summary>
			public const int RequestAccessTokenAuthorizationCodeAppNotMatch = unchecked((int)0x800F0623);

			/// <summary>
			/// 请求访问Token授权未指定刷新Token
			/// </summary>
			public const int RequestAccessTokenAuthorizationRefreshTokenMissing = unchecked((int)0x800F0624);

			/// <summary>
			/// 请求访问Token授权刷新Token不存在
			/// </summary>
			public const int RequestAccessTokenAuthorizationRefreshTokenNotExist = unchecked((int)0x800F0625);

			/// <summary>
			/// 请求访问Token授权刷新Token不属于当前应用
			/// </summary>
			public const int RequestAccessTokenAuthorizationRefreshTokenNotMatch = unchecked((int)0x800F0626);

			/// <summary>
			/// 请求访问Token授权刷新Token无效
			/// </summary>
			public const int RequestAccessTokenAuthorizationRefreshTokenError = unchecked((int)0x800F0627);

			/// <summary>
			/// 开发者应用程序选择的权限码不存在
			/// </summary>
			public const int DeveloperApplicatinNoFoundCode = unchecked((int)0x800F0628);

			/// <summary>
			/// 开发者应用程序在非开发中状态不能更新API权限信息
			/// </summary>
			public const int DeveloperApplicatinInvalidStateCannotUpdatePermission = unchecked((int)0x800F0629);

			/// <summary>
			/// 你的应用处于无效状态.
			/// </summary>
			public const int ApplicationStateError = unchecked((int)0x800F0630);

			/// <summary>
			/// 你的账号已禁用.
			/// </summary>
			public const int UserAccountDisable = unchecked((int)0x800F0631);

			/// <summary>
			/// 开发者应用程序没有选择产品API，不能提交审核
			/// </summary>
			public const int DeveloperApplicatinUnGroupCannotSubmitToApprove = unchecked((int)0x800F0632);

			/// <summary>
			/// 已存在相同的开发者应用程序名称:{0}
			/// </summary>
			public const int ExistsSameDeveloperAppName = unchecked((int)0x800F0633);

			/// <summary>
			/// 请指定要验证的Token.
			/// </summary>
			public const int TokenCannotBeNull = unchecked((int)0x800F0634);

			/// <summary>
			/// 请指定要验证的权限码.
			/// </summary>
			public const int PermissionCodeCannotNull = unchecked((int)0x800F0635);

			/// <summary>
			/// 请求的Token不存在
			/// </summary>
			public const int AccessTokenNotExist = unchecked((int)0x800F0636);

			/// <summary>
			/// 访问Token验证失败，请检查是否禁用或过期,权限码是否匹配
			/// </summary>
			public const int AccessTokenValidateFail = unchecked((int)0x800F0637);

			/// <summary>
			/// 客户账号已处于失效状态，授权终止
			/// </summary>
			public const int CustomerIsForbiddenAccessTokenFail = unchecked((int)0x800F0638);

			/// <summary>
			/// 请求的重定向地址格式不正确
			/// </summary>
			public const int RequestAccessTokenCallbackInvalidFormat = unchecked((int)0x800F0639);

			/// <summary>
			/// 开发者应用程序在非开发中状态不能修改信息
			/// </summary>
			public const int DeveloperApplicatinInvalidStateCannotUpdate = unchecked((int)0x800F0640);

			/// <summary>
			/// 请求的开发者应用不存在
			/// </summary>
			public const int DeveloperApplicatinUnExists = unchecked((int)0x800F0641);

				}

		public static class StringCodes
		{
			/// <summary>
			/// Internal error
			/// </summary>
			public const string InternalError = "800F0001";

			/// <summary>
			/// The request parameter can not null
			/// </summary>
			public const string ValidationRequestParameterNull = "800F0002";

			/// <summary>
			/// {0}不能为空
			/// </summary>
			public const string ArgumentCannotBeNullOrEmptyString = "800F0003";

			/// <summary>
			/// {0}不存在
			/// </summary>
			public const string ArgumentCannotBeNull = "800F0004";

			/// <summary>
			/// Login failed
			/// </summary>
			public const string LoginFailed = "800F0101";

			/// <summary>
			/// Access denied
			/// </summary>
			public const string AccessDenied = "800F0102";

			/// <summary>
			/// 系统已存在相同的应用名称:{0}
			/// </summary>
			public const string ExistsSameApplicationName = "800F0501";

			/// <summary>
			/// 系统不存在此应用
			/// </summary>
			public const string NoFoundApplication = "800F0502";

			/// <summary>
			/// 系统已存在相同的应用英文名称:{0}
			/// </summary>
			public const string ExistsSameApplicationEnName = "800F0503";

			/// <summary>
			/// 当前用户已经为启用状态，不能再次转为启用状态
			/// </summary>
			public const string CannotChangeUserStateToEnabled = "800F0530";

			/// <summary>
			/// 当前用户已经为禁用状态，不能再次转为禁用状态
			/// </summary>
			public const string CannotChangeUserStateToDisabled = "800F0531";

			/// <summary>
			/// 系统已存在相同的用户名:{0}
			/// </summary>
			public const string ExistsSameUserLoginName = "800F0532";

			/// <summary>
			/// 用户名或密码无效
			/// </summary>
			public const string LoginNameOrPasswordInvalid = "800F0533";

			/// <summary>
			/// 已存在相同的角色名称
			/// </summary>
			public const string ExistsSameRoleName = "800F0534";

			/// <summary>
			/// 已存在相同的角色代码
			/// </summary>
			public const string ExistsSameRoleCode = "800F0535";

			/// <summary>
			/// 系统不存在角色代码:{0}
			/// </summary>
			public const string NoFoundRoleCode = "800F0536";

			/// <summary>
			/// 旧密码不匹配
			/// </summary>
			public const string OldPassowrdNotMatch = "800F0537";

			/// <summary>
			/// 系统已存在相同的员工号:{0}
			/// </summary>
			public const string ExistsSameEmployeeNo = "800F0538";

			/// <summary>
			/// 无效的Email
			/// </summary>
			public const string InvalidEmail = "800F0539";

			/// <summary>
			/// 密码不允许为空
			/// </summary>
			public const string PasswordCannotBeNull = "800F0540";

			/// <summary>
			/// 当前用户已被禁用
			/// </summary>
			public const string LoginNameIsApproved = "800F0541";

			/// <summary>
			/// 无效的手机号码
			/// </summary>
			public const string InvalidPhone = "800F0542";

			/// <summary>
			/// 用户名不允许为空
			/// </summary>
			public const string IdentityCannotBeNull = "800F0543";

			/// <summary>
			/// 调用来源不允许为空
			/// </summary>
			public const string SourceCannotBeNull = "800F0544";

			/// <summary>
			/// 用户{0}不存在
			/// </summary>
			public const string IdentityNotExist = "800F0545";

			/// <summary>
			/// 登陆名称不允许为空
			/// </summary>
			public const string LoginNameCannotBeNull = "800F0546";

			/// <summary>
			/// 邮箱不允许为空
			/// </summary>
			public const string EmailCannotBeNull = "800F0547";

			/// <summary>
			/// 系统不存在权限代码:{0}
			/// </summary>
			public const string NoFoundPermissionCode = "800F0550";

			/// <summary>
			/// 不支持的权限类型
			/// </summary>
			public const string UnSupportPermissionType = "800F0551";

			/// <summary>
			/// 已存在相同的权限名称
			/// </summary>
			public const string ExistsSamePermissionName = "800F0552";

			/// <summary>
			/// 当前应用不存在权限代码:{0}
			/// </summary>
			public const string AppNoFoundPermissionCode = "800F0553";

			/// <summary>
			/// 不存在该菜单ID:{0}
			/// </summary>
			public const string NoFoundMenuId = "800F0570";

			/// <summary>
			/// 菜单ID:{0}存在子菜单，不允许删除
			/// </summary>
			public const string MenuHasChild = "800F0571";

			/// <summary>
			/// 当前应用不存在该菜单ID:{0}
			/// </summary>
			public const string ApplicationNoFoundMenuId = "800F0572";

			/// <summary>
			/// 已存在相同的分组名称
			/// </summary>
			public const string ExistsSameApiPermissionGroupName = "800F0572";

			/// <summary>
			/// 已存在相同的分组编码
			/// </summary>
			public const string ExistsSameApiPermissionGroupCode = "800F0573";

			/// <summary>
			/// 不存在API权限分组代码:{0}
			/// </summary>
			public const string NoFoundApiPermissionGroupCode = "800F0574";

			/// <summary>
			/// 需要对外开放的权限码:{0}
			/// </summary>
			public const string IsOpenedPermissionCode = "800F0575";

			/// <summary>
			/// 需要客户授权的权限代码:{0}
			/// </summary>
			public const string IsCustomerGrantedPermissionCode = "800F0576";

			/// <summary>
			/// 已存在相同的权限编码:{0}
			/// </summary>
			public const string ExistsSamePermissionCode = "800F0577";

			/// <summary>
			/// Token已过期，不能设置为启用
			/// </summary>
			public const string TokenExpiredCannotSetEnable = "800F0600";

			/// <summary>
			/// 授权码已过期或已使用，不能设置为启用
			/// </summary>
			public const string AuthorizationCodeCannotSetEnable = "800F0601";

			/// <summary>
			/// 开发者应用程序名称不能为空
			/// </summary>
			public const string DeveloperApplicatinNameCannotBeNull = "800F0602";

			/// <summary>
			/// 开发者应用程序所属账号不能为空
			/// </summary>
			public const string DeveloperApplicatinUserCannotBeNull = "800F0603";

			/// <summary>
			/// 开发者应用程序回调地址不能为空
			/// </summary>
			public const string DeveloperApplicatinCallbackUrlCannotBeNull = "800F0604";

			/// <summary>
			/// 开发者应用程序在非开发中状态不能提交审核
			/// </summary>
			public const string DeveloperApplicatinInvalidStateCannotSubmitToApprove = "800F0605";

			/// <summary>
			/// 开发者应用程序不是审核通过，可能在非法的状态下提审
			/// </summary>
			public const string DeveloperApplicatinInvalidStateCannotBeApproved = "800F0606";

			/// <summary>
			/// 开发者应用程序在当前的状态下不能驳回
			/// </summary>
			public const string DeveloperApplicatinInvalidStateToBeReject = "800F0607";

			/// <summary>
			/// 不支持的请求授权类型
			/// </summary>
			public const string CustomerAuthorizationUnsupportType = "800F0608";

			/// <summary>
			/// 请求授权的应用不存在
			/// </summary>
			public const string CustomerAuthorizationAppNotExist = "800F0609";

			/// <summary>
			/// 请求授权应用的重定向地址与应用注册时回调地址非同源
			/// </summary>
			public const string CustomerAuthorizationRedirectUrlIsNotCognatedWithRegisterCallbcakUrl = "800F0610";

			/// <summary>
			/// 未指定授权范围参数
			/// </summary>
			public const string CustomerAuthorizationScopeMustHasVal = "800F0611";

			/// <summary>
			/// 请求的授权部分不存在，请重新确认授权范围
			/// </summary>
			public const string CustomerAuthorizationScopePartNotExist = "800F0612";

			/// <summary>
			/// 未指定请求授权响应类型(responseType)
			/// </summary>
			public const string CustomerAuthorizationResponseTypeMissing = "800F0613";

			/// <summary>
			/// 未指定重定向参数(redirect_uri)
			/// </summary>
			public const string CustomerAuthorizationRedirectUriMissing = "800F0614";

			/// <summary>
			/// 未指定应用Clientid参数
			/// </summary>
			public const string CustomerAuthorizationClientIdMissing = "800F0615";

			/// <summary>
			/// 未指定应用授权范围参数(scope)
			/// </summary>
			public const string CustomerAuthorizationScopeMissing = "800F0616";

			/// <summary>
			/// 授权范围与应用授权不匹配，请重新确认授权范围(scope)
			/// </summary>
			public const string CustomerAuthorizationScopeNotMatch = "800F0617";

			/// <summary>
			/// 请求访问Token应用密钥参数未指定.(Client_secret)
			/// </summary>
			public const string RequestAccessTokenSecretMissing = "800F0618";

			/// <summary>
			/// 请求访问Token应用密钥不匹配.(Client_secret)
			/// </summary>
			public const string RequestAccessTokenSecretNotMatch = "800F0619";

			/// <summary>
			/// 请求访问Token授权类型未指定.(Grant_type)
			/// </summary>
			public const string RequestAccessTokenGrantTypeMissing = "800F0620";

			/// <summary>
			/// 请求访问Token授权类型指定错误，目前支持authorization_code和refresh_token两种方式
			/// </summary>
			public const string RequestAccessTokenGrantTypeError = "800F0621";

			/// <summary>
			/// 请求访问Token授权未指定授权码.
			/// </summary>
			public const string RequestAccessTokenAuthorizationCodeMissing = "800F0622";

			/// <summary>
			/// 请求访问的授权码不存在.
			/// </summary>
			public const string RequestAccessTokenAuthorizationCodeNotExist = "800F0623";

			/// <summary>
			/// 请求访问的授权码无效.
			/// </summary>
			public const string RequestAccessTokenAuthorizationCodeError = "800F0622";

			/// <summary>
			/// 请求访问的授权码不属于当前应用
			/// </summary>
			public const string RequestAccessTokenAuthorizationCodeAppNotMatch = "800F0623";

			/// <summary>
			/// 请求访问Token授权未指定刷新Token
			/// </summary>
			public const string RequestAccessTokenAuthorizationRefreshTokenMissing = "800F0624";

			/// <summary>
			/// 请求访问Token授权刷新Token不存在
			/// </summary>
			public const string RequestAccessTokenAuthorizationRefreshTokenNotExist = "800F0625";

			/// <summary>
			/// 请求访问Token授权刷新Token不属于当前应用
			/// </summary>
			public const string RequestAccessTokenAuthorizationRefreshTokenNotMatch = "800F0626";

			/// <summary>
			/// 请求访问Token授权刷新Token无效
			/// </summary>
			public const string RequestAccessTokenAuthorizationRefreshTokenError = "800F0627";

			/// <summary>
			/// 开发者应用程序选择的权限码不存在
			/// </summary>
			public const string DeveloperApplicatinNoFoundCode = "800F0628";

			/// <summary>
			/// 开发者应用程序在非开发中状态不能更新API权限信息
			/// </summary>
			public const string DeveloperApplicatinInvalidStateCannotUpdatePermission = "800F0629";

			/// <summary>
			/// 你的应用处于无效状态.
			/// </summary>
			public const string ApplicationStateError = "800F0630";

			/// <summary>
			/// 你的账号已禁用.
			/// </summary>
			public const string UserAccountDisable = "800F0631";

			/// <summary>
			/// 开发者应用程序没有选择产品API，不能提交审核
			/// </summary>
			public const string DeveloperApplicatinUnGroupCannotSubmitToApprove = "800F0632";

			/// <summary>
			/// 已存在相同的开发者应用程序名称:{0}
			/// </summary>
			public const string ExistsSameDeveloperAppName = "800F0633";

			/// <summary>
			/// 请指定要验证的Token.
			/// </summary>
			public const string TokenCannotBeNull = "800F0634";

			/// <summary>
			/// 请指定要验证的权限码.
			/// </summary>
			public const string PermissionCodeCannotNull = "800F0635";

			/// <summary>
			/// 请求的Token不存在
			/// </summary>
			public const string AccessTokenNotExist = "800F0636";

			/// <summary>
			/// 访问Token验证失败，请检查是否禁用或过期,权限码是否匹配
			/// </summary>
			public const string AccessTokenValidateFail = "800F0637";

			/// <summary>
			/// 客户账号已处于失效状态，授权终止
			/// </summary>
			public const string CustomerIsForbiddenAccessTokenFail = "800F0638";

			/// <summary>
			/// 请求的重定向地址格式不正确
			/// </summary>
			public const string RequestAccessTokenCallbackInvalidFormat = "800F0639";

			/// <summary>
			/// 开发者应用程序在非开发中状态不能修改信息
			/// </summary>
			public const string DeveloperApplicatinInvalidStateCannotUpdate = "800F0640";

			/// <summary>
			/// 请求的开发者应用不存在
			/// </summary>
			public const string DeveloperApplicatinUnExists = "800F0641";

				}

        public static string ToHex(this int value)
        {
            return "0x" + value.ToString("X");
        }
    }
}// end of namespace DX.OMS.Common